import {StyleSheet} from 'react-native';
import Theme from '../../utils/Theme';

export const styles = StyleSheet.create({
  modalContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    // opacity: 0
  },
  modalView: {
    width: '90%',
    backgroundColor: 'white',
    borderRadius: 10,
    padding: 20,
    alignItems: 'center',
  },
  iconContainer: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    width: '60%',
    marginBottom: 20,
  },
  title: {
    fontSize: 18,
    fontWeight: 'bold',
    marginBottom: 20,
    textAlign: 'center',
    color: 'black',
    width: '70%',
  },
  steps: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    width: '80%',
    marginBottom: 20,
  },
  stepButton: {
    height: 40,
    width: 40,
    borderRadius: 100,
    backgroundColor: 'white',
    borderColor: 'grey',
    justifyContent: 'center',
    alignItems: 'center',
  },
  stepButtonActive: {
    backgroundColor: 'black',
  },
  stepButtonText: {
    fontSize: 20,
    color: 'grey',
  },
  stepButtonTextActive: {
    color: 'white',
  },
  stepImageContainer: {
    width: 250,
    height: 200,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 20,
  },
  stepImage: {
    width: '100%',
    height: '100%',
    resizeMode: 'contain',
  },
  instructions: {
    fontSize: 16,
    fontWeight: 'bold',
    textAlign: 'center',
  },
  postButton: {
    backgroundColor: 'black',
    paddingVertical: 11,
    paddingHorizontal: 50,
    borderRadius: 20,
    flexDirection: 'row',
    alignItems: 'center',
  },
  postButtonText: {
    color: 'white',
    fontWeight: '900',
  },
  close: {
    position: 'absolute',
    right: 10,
    top: 10,
    backgroundColor: 'black',
    width: 20,
    height: 20,
    borderRadius: 100,
    justifyContent: 'center',
    alignItems: 'center',
  },
  activeIcon: {
    backgroundColor: 'black',
    padding: 2,
    borderRadius: 50,
  },
  hiddenViewShot: {
    position: 'absolute',
    zIndex: -1,
    flex: 1,
    top: -9999,
    left: -9999,
    height: '100%',
    width: '100%',
  },
  viewShotGradient: {
    flex: 1,
    padding: 10,
    justifyContent: 'center',
    alignItems: 'center',
  },
  viewShotContent: {
    margin: 20,
    borderRadius: 10,
    width: '90%',
  },
  viewShotTextContainer: {
    borderRadius: 20,
    paddingHorizontal: 20,
    backgroundColor: 'rgba(255, 255, 255, 0.4)',
    paddingVertical: 40,
  },
  viewShotText: {
    color: 'black',
    fontSize: 24,
    textAlign: 'center',
    fontWeight: 'bold',
  },
  viewShotImage: {
    width: 60,
    height: 90,
    alignSelf: 'center',
    resizeMode: 'contain',
  },
  viewShotLinkContainer: {
    alignSelf: 'center',
    borderRadius: 10,
    height: 60,
    width: 160,
  },
  linkImage: {
    width: '100%',
    height: '100%',
    resizeMode: 'contain',
  },
  pasteLinkContainer: {
    width: 180,
    height: 50,
    flexDirection: 'row',
    alignSelf: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.3)',
    borderRadius: 10,
    marginTop: 20,
  },
  pasteImage: {
    width: '28%',
    height: '100%',
    resizeMode: 'contain',
    borderTopLeftRadius: 10,
    borderBottomLeftRadius: 10,
  },
  viewShotLogo: {
    width: 140,
    height: 50,
    position: 'absolute',
    bottom: 100,
  },
  iconImage: {
    width: 50,
    height: 50,
  },
  stepText: {
    textAlign: 'center',
    fontSize: 14,
    fontWeight: 'bold',
    color: 'black',
    marginBottom: 10,
    // height: 40,
  },
  viewShotLinkContainer2: {
    alignSelf: 'center',
    borderRadius: 10,
    height: 50,
    width: 160,
    backgroundColor: '#FFFFFF',
    borderRadius: 10,
    justifyContent: 'center',
    alignItems: 'center',
  },
});
