import {StyleSheet} from 'react-native';
import Theme from '../../../utils/Theme';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: Theme.white,
    // padding: 20,
  },
  setView: {
    marginTop: Theme.wp('2'),
    width: '90%',
    alignSelf: 'center',
  },
  vipText: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  vipContainer: {
    flexDirection: 'row',
    backgroundColor: '#F5F5F5',
    marginVertical: Theme.wp('2'),
    borderRadius: 10,
    justifyContent: 'space-between',
    paddingVertical: 15,
  },

  vipContainer1: {
    flexDirection: 'row',
    backgroundColor: '#F5F5F5',
    marginVertical: Theme.wp('2'),
    borderRadius: 10,
    justifyContent: 'space-between',
    paddingVertical: 15,
    alignItems: 'center',
  },

  vipContainer2: {
    flexDirection: 'row',
    backgroundColor: '#F5F5F5',
    marginVertical: Theme.wp('2'),
    borderRadius: 10,
    justifyContent: 'space-between',
    paddingVertical: 15,
    alignItems: 'center',
  },
  hintItem: {
    alignItems: 'center',
    justifyContent: 'center',
    width: '20%',
  },
  hintItem1: {
    alignItems: 'center',
    justifyContent: 'center',
    // width: '65%',
    left: -20,
  },
  hintText: {
    color: 'black',
    fontSize: 11,
    textAlign: 'center',
  },

  hintText1: {
    color: 'black',
    fontSize: 11,
    width: 180,
    left: 20,
  },
  messageContainer: {
    width: '100%',
    backgroundColor: 'rgba(255, 255, 255, 0.4)',
    marginTop: Theme.wp('5'),
    borderRadius: 30,
    marginBottom: Theme.wp('6'),
    paddingBottom: 20,
  },
  rlyText: {
    textAlign: 'center',
    color: 'white',
    fontSize: Theme.wp('4'),
    fontWeight: '900',
  },
  socialButtonContainer: {
    marginTop: Theme.wp('4'),
    width: '50%',
    backgroundColor: '#F5F5F5',
    alignSelf: 'center',
    borderRadius: 30,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: Theme.wp('8'),
    paddingVertical: 17,
  },
  socialText: {
    color: Theme.black,
    marginLeft: Theme.wp('4'),
    fontSize: Theme.wp('5'),
    fontWeight: 'bold',
  },
  whoSentContainer: {
    width: '80%',
    backgroundColor: '#9575DE',
    alignSelf: 'center',
    borderRadius: 30,
    alignItems: 'center',
    paddingVertical: 17,
    marginTop: Theme.wp(20),
  },
  whoSentText: {
    color: Theme.white,
    fontSize: Theme.wp('5'),
    fontWeight: 'bold',
  },
  hiddenViewShot: {
    position: 'absolute',
    zIndex: -1,
    flex: 1,
    top: -9999,
    left: -9999,
    height: '100%',
    width: '100%',
  },
  viewShotGradient: {
    flex: 1,
    padding: 10,
    justifyContent: 'center',
    alignItems: 'center',
  },
  viewShotContent: {
    margin: 20,
    borderRadius: 10,
    width: '90%',
  },
  viewShotTextContainer: {
    borderRadius: 20,
    paddingHorizontal: 20,
    backgroundColor: 'rgba(255, 255, 255, 0.4)',
    paddingVertical: 40,
  },
  viewShotText: {
    color: 'black',
    fontSize: 24,
    textAlign: 'center',
    fontWeight: 'bold',
  },
  viewShotImage: {
    width: 60,
    height: 90,
    alignSelf: 'center',
    resizeMode: 'contain',
  },
  viewShotLinkContainer: {
    alignSelf: 'center',
    borderRadius: 10,
    height: 60,
    width: 160,
  },
  viewShotLogo: {
    width: 140,
    height: 50,
    position: 'absolute',
    bottom: 100,
  },
  buttonContainer: {
    flexDirection: 'row',
    justifyContent: 'space-evenly',
    width: '80%',
    alignItems: 'center',
    alignSelf: 'center',
    marginTop: 20,
    marginBottom: 20,
  },
  button: {
    margin: 10,
    borderRadius: 100,
    overflow: 'hidden',
    width: 35,
    height: 35,
    alignItems: 'center',
  },
  selectedButton: {
    borderWidth: 2,
    borderColor: '#000',
  },
  buttonGradient: {
    borderRadius: 100,
    justifyContent: 'center',
    alignItems: 'center',
    width: '100%',
    height: '100%',
  },
});
